version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
      - mvn install
      - mvn deploy
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/myrewardengine-0.0.1-SNAPSHOT.jar deploy/lib
      - aws s3 cp target/myrewardengine-0.0.1-SNAPSHOT.jar s3://myrewardcore/snapshot/myrewardengine-0.0.1-SNAPSHOT.jar
      - mvn deploy:deploy-file -Dfile=target/myrewardengine-0.0.1-SNAPSHOT.jar -DgroupId=com.myreward -DartifactId=myrewardcore -Dversion=0.0.1 -Dpackaging=jar -Durl=s3://myreward/snapshot
artifacts:
  type: zip
  files:
    - deploy/lib/myrewardengine-0.0.1-SNAPSHOT.jar
