version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn test
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir deploy
      - mkdir deploy/lib
      - cp target/myrewardengine-0.0.1-SNAPSHOT.jar deploy/lib
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket testbucket-77 --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - deploy/lib/myrewardengine-0.0.1-SNAPSHOT.jar
    - NewSamTemplate.yaml
